### ISSUE TITLE
Assembly version is 0.0.0.0

### ISSUE THREAD

**Issue by ltrzesniewski** [Fody/EmptyConstructor#16]
The published weaver assembly version is 0.0.0.0, which causes Fody to pick the wrong EmptyConstructor version when multiple versions are available in the packages directory.

- The `Directory.Build.props` file contains `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`
- There's also a `CommonAssemblyInfo.cs` file which is not used by any project (and contains an old version number anyway)

I just noticed the outdated/unused `CommonAssemblyInfo.cs` issue is also present in some other addins of yours @SimonCropp, so you way want to take a look at that.

**Comment by SimonCropp** [comment]
thanks. will review other weavers
