### ISSUE TITLE
After update to version 3.0.0, compile throws System.NullReferenceException

### ISSUE THREAD

**Issue by agisbert-iti-es** [Fody/EmptyConstructor#167]
**Description**

After update versions on project:

- From 1.1.7 to 3.0.0 - EmptyConstructor.Fody
- From 1.29.2 to 6.1.0 - Fody
- From 1.19.12 to 3.0.0 - Virtuosity.Fody

With "FodyWeavers.xml" with this configuration:

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <EmptyConstructor />
  <Virtuosity />
</Weavers>
```

The compilers throws en error "System.NullReferenceException":

```
Error		Fody: An unhandled exception occurred:
Exception:
  Failed to execute weaver C:\Workspace\eVinfoPOL\sources\packages\EmptyConstructor.Fody.3.0.0\build\..\weaver\EmptyConstructor.Fody.dll
Type:
  System.Exception
  StackTrace:
     en InnerWeaver.ExecuteWeavers() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 206
     en InnerWeaver.Execute() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 111
Source:
  FodyIsolated
TargetSite:
  Void ExecuteWeavers()
  Referencia a objeto no establecida como instancia de un objeto.
Type:
  System.NullReferenceException
  StackTrace:
   en ModuleWeaver.Execute()
   en InnerWeaver.ExecuteWeavers() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 178
Source:
  EmptyConstructor.Fody
```

Is there any way to get info about the source of NullReferenceException?

I guess Fody is missing something on project configuration, but I can't find what it is.

Thanks in advance.
Regards

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
