### ISSUE TITLE
Config file too?

### ISSUE THREAD

**Issue by Sn3b** [Fody/EmptyConstructor#7]
Is it possible to also embed the config file?

**Comment by SimonCropp** [comment]
What config file and why?

**Comment by Sn3b** [comment]
The app.config file, because either I hardcode the ID's of a couple of elements, or I have them in a config file that needs to be embedded. It's for an executable that'll be recompiled every time with the new ID's, so that there's only 1 file to download.

**Comment by SimonCropp** [comment]
I think u have raised this in the wrong repo

**Comment by Sn3b** [comment]
Oops... Sorry...

**Comment by SimonCropp** [comment]
no worries
