### ISSUE TITLE
Logging Severity

### ISSUE THREAD

**Issue by marcoerni** [Fody/EmptyConstructor#8]
Is it possible to decrease the logging severity for the log message which stating that a empty constructor was created from severity info to debug? Currently the EmptyConstructor weaver is extremely chatty and fills up our build log.

**Comment by SimonCropp** [comment]
Sure. Send me a PR and I will release a new version

**Comment by SimonCropp** [comment]
deployed

**Comment by marcoerni** [comment]
great, thanks!
